### ISSUE TITLE
Is there a remix button possible

### ISSUE THREAD

**Issue by IPikuch** [krystalgamer/stem-player-emulator#11]
Very cool plugin but it'd be better if it could have the remix option # # #

**Comment by krystalgamer** [comment]
the goal of the project is to simply allow the download of the tracks in the default mode(MP3) and WAV mode.

if you're looking into remixing capabilities look into something like: https://github.com/nn9dev/stemplayerplayer

**Comment by GoodnessEzeokafor** [comment]
how do i download ?
