### ISSUE TITLE
Issue with iOS

### ISSUE THREAD

**Issue by Bartschey** [krystalgamer/stem-player-emulator#15]
Hey there, tried following the provided steps for mobile and after enabling and clicking user scripts, it returns "Failed to get  init data"

**Comment by krystalgamer** [comment]
@mmattbtw can you help?

**Comment by vxkernel** [comment]
This happens if you haven't set a Userscripts Directory in the Usercripts app, add a directory in the app and the error will disappear

**Comment by Zasou999** [comment]
Hello I have followed all steps provided for the iOS emulator download but as soon as I go onto stemplayer.com I can’t seem to get into the stem splitter area where albums are it tells me “failed to connect” when I try.

**Comment by Bartschey** [comment]
That fix worked for me, thanks :)

**Comment by Bartschey** [comment]
Setting the directory worked for me, thanks :)
