### ISSUE TITLE
Not able to play audio

### ISSUE THREAD

**Issue by fafamobile** [krystalgamer/stem-player-emulator#2]
Audio is not able to be played when on the stem player website

**Comment by thatcherclough** [comment]
You also can't download the files from the site anymore. They must've patched it

**Comment by fafamobile** [comment]
> You also can't download the files from the site anymore. They must've patched it

yea they patched, need update asap

**Comment by SageSystems** [comment]
same issue, more info on the error
response from stem request url `{"error":{"code":401,"error":"unauthorized","message":"JWT must be provided"}}`

**Comment by vjacksonnn** [comment]
I am having the same issue unable to play audio from stemplayer website from the "play button"

**Comment by krystalgamer** [comment]
Fixed it please update

**Comment by fafamobile** [comment]
> Fixed it please update

Now just wont recognise the stem player when trying to connect

**Comment by thatcherclough** [comment]
Same for me

**Comment by krystalgamer** [comment]
they're pushing updates quick lmfao

**Comment by edinabazi** [comment]
Yeah USB not getting detected since 0.4 :/

**Comment by chadhyatt** [comment]
holy shit how are they patching this so quickly lol
dude i think your best bet when updating this next is obfucating it or smth.. like dang theyre quick man

**Comment by fafamobile** [comment]
how?

**Comment by lumaaaaaa** [comment]
> holy shit how are they patching this so quickly lol dude i think your best bet when updating this next is obfucating it or smth.. like dang theyre quick man

obfuscate an open source program? nah.

**Comment by chadhyatt** [comment]
> > holy shit how are they patching this so quickly lol dude i think your best bet when updating this next is obfucating it or smth.. like dang theyre quick man
> 
> obfuscate an open source program? nah.

I mean when they're patching it within minutes...

**Comment by krystalgamer** [comment]
i'd never obfuscate it

**Comment by fafamobile** [comment]
how do u do that

**Comment by fafamobile** [comment]
is it best to update at a later date? or are u working on something

**Comment by edinabazi** [comment]
Got rid of the extra `s` in line 322 at the end and it works!

**Comment by Este-iv** [comment]
Edinabazi is correct. you can remove the s and it will work.
the catch is that you can't download the album. It has been working tack by track.

**Comment by krystalgamer** [comment]
fixed now
> the catch is that you can't download the album

that's by design
