### ISSUE TITLE
Chrome only showing Play button for each song

### ISSUE THREAD

**Issue by phewcharyztik** [krystalgamer/stem-player-emulator#20]
Not sure if it's just because of how the website has been updated, but it's only showing PLAY next to each track title now on Chrome. There isn't a download button anymore or any way to play the Stems separately.

**Comment by krystalgamer** [comment]
that's how the website works. go to platform to actually download the tracks

**Comment by phewcharyztik** [comment]
Thanks

**Comment by krystalgamer** [comment]
@phewcharyztik wait for the new version, a lot of people have been asking me for this feature.
