### ISSUE TITLE
[iOS] Userscripts: failed to get init data

### ISSUE THREAD

**Issue by 0zumi** [krystalgamer/stem-player-emulator#22]
Following the instructions for iOS i always come across this problem:
![EAB889D2-00B7-42CE-BEDD-81EBE8CBD3FE](https://user-images.githubusercontent.com/101345667/157692996-f39c8a78-a9fa-42a5-8ccd-fe185adb1851.png)

**Comment by krystalgamer** [comment]
https://github.com/krystalgamer/stem-player-emulator/issues/15
