### ISSUE TITLE
Suggestion for top menu

### ISSUE THREAD

**Issue by Fillygroove** [krystalgamer/stem-player-emulator#27]
I know this is more of an aesthetic thing than a bug fix but I think that it would be better if the mode/download-on-play options were triggered by a hotkey on computers (maybe pressing z or something toggles the menu, maybe an option to change which key it is if this is implemented) instead of always being on there; Phones are fine as is imo. It's not that big of an issue but I believe it could look nicer.

Also I wanna say thank you for gracing the world with this, means a lot!

**Comment by krystalgamer** [comment]
features over looks was my approach. there's a lot of things that can be done to improve the aesthetics of it, but I don't really want to focus on that. If anyone wants to do so I'm open to review any PR.

Thanks for the nice words!
