### ISSUE TITLE
Failure to play tracks

### ISSUE THREAD

**Issue by fafamobile** [krystalgamer/stem-player-emulator#29]
Able to access tracks but "track failed to load"

**Comment by HarryBiceps** [comment]
Same here! I swear if thing just got patched I am so done. But yeah, when I press play with download on play on it just says track failed to load.

**Comment by HarryBiceps** [comment]
Actual stem making still works for me though

**Comment by krystalgamer** [comment]
they updated multiple parts of the website, the login part now requires password and the device now has a challenge to solve (PoW) before getting access to tracks. 
 the password part is not something I will fix, but the device-challenge seems doable. my schedule is a little busy atm so don't expect a fix ASAP.

**Comment by onlinedictionary** [comment]
**Anbody got the the Donda 2 files? I usually just played it on the website. D=**

**Comment by krystalgamer** [comment]
update
