### ISSUE TITLE
STEM PLAYER

### ISSUE THREAD

**Issue by PurpleFlameBeats** [krystalgamer/stem-player-emulator#31]
Needs Fixing

"TRACK FAILED TO LOAD"

![Web capture_31-3-2022_22330_www stemplayer com](https://user-images.githubusercontent.com/102777559/161183880-21b0d424-9ed9-4901-a434-c72e7b031312.jpeg)

**Comment by krystalgamer** [comment]
read the notice, if you want the emulator to be fixed consider donating.
