### ISSUE TITLE
TRACK FAILED TO LOAD

### ISSUE THREAD

**Issue by zhongxx0227** [krystalgamer/stem-player-emulator#32]
I can't play donda or donda2 because "TRACK FAILED TO LOAD".

**Comment by gandolino** [comment]
Same

**Comment by krystalgamer** [comment]
it's on the readme.

Kano has been updating their website so the emulator might stop working at any time without warning. If you just want to listen to the album then I suggest you to find mirrors online, if you wish to support the emulator then you can donate [here](https://www.paypal.com/donate/?hosted_button_id=N6QZL2267QYLU). 

Money will be used to buy the stemplayer and teardown for further reverse-engineering purposes.

**Comment by gandolino** [comment]
Thanks, ;)

Il giorno dom 3 apr 2022 alle 19:13 Jose Silva ***@***.***>
ha scritto:
