### ISSUE TITLE
newest update wont connect

### ISSUE THREAD

**Issue by killakawsta** [krystalgamer/stem-player-emulator#5]
just updated newest script and it doesnt connect now it shows up the popup to connect and then says failed to connect if you click off 

https://user-images.githubusercontent.com/72592678/155633051-cf04bc36-822d-48cb-90ac-848c1e1ad153.mp4

**Comment by SupremeTitan48** [comment]
Same issue as mine

**Comment by spiiritual** [comment]
yeah its because there's a random s where the new commit added a serial number

**Comment by killakawsta** [comment]
> Same issue as mine

yea i saw yours as soon as i uploaded

**Comment by SupremeTitan48** [comment]
> yeah its because there's a random s where the new commit added a serial number

Can we fix that?

**Comment by allowedmouth** [comment]
i know nothing about coding, just here until this bug is fixed for the 2nd round of song uploads

**Comment by SupremeTitan48** [comment]
Tried removing the S in the tampermonkey editor, it is definitely more than that, or maybe I'm stupid

**Comment by spiiritual** [comment]
that's odd, it worked for me, did you make sure to save it under file > save in the editor?

**Comment by SupremeTitan48** [comment]
> that's odd, it worked for me, did you make sure to save it under file > save in the editor?

Is it the e.sn part?

**Comment by SupremeTitan48** [comment]
> that's odd, it worked for me, did you make sure to save it under file > save in the editor?

Is it the e.sn part?

**Comment by krystalgamer** [comment]
yeah
get my update

**Comment by allowedmouth** [comment]
> 
the "here" link doesnt bring me to tempermonkey tab...why is this?

**Comment by SageSystems** [comment]
> > 
> 
> the "here" link doesnt bring me to tempermonkey tab...why is this?

click raw and that will take you to install

**Comment by krystalgamer** [comment]
it's fixed now, i messed up big time when fixing the 401 lmfao
