### ISSUE TITLE
They seem to be blacklisting serial numbers

### ISSUE THREAD

**Issue by chadhyatt** [krystalgamer/stem-player-emulator#8]
No clue how or why, but they're seeming to instantly blacklist the "JWD"/Serial Numbers used in this repository. No clue on how this can be circumvented, but gl.

**Comment by krystalgamer** [comment]
if they do, then they'll have a huge problem lmfao

**Comment by SageSystems** [comment]
works on my machine™ (joke response aside this doesn't seem to be the case)

**Comment by krystalgamer** [comment]
closing by now since it's not true yet

**Comment by jch254** [comment]
I'll leave this here https://www.google.com/search?q=stemplayer++grailed+box&sxsrf=APq-WBvzq33kC_vnRgD4VA__RSDLQ8jKqw:1645755455732&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiEts3q5Jn2AhWYzTgGHXIOCyIQ_AUoAnoECCIQBA&biw=2534&bih=1297&dpr=1

**Comment by krystalgamer** [comment]
I'd like to make it clear that I don't own a stem player, this project was developed simply by RE the protocol.

@jch254 has the spirit :)
